from novel_agent.plugins.base import (
    PluginBase,
    PluginMeta,
    PluginType,
    PluginContext,
    PluginEvent,
    PipelineHookPlugin,
    QualityGuardPlugin,
    ExporterPlugin,
    LLMProviderPlugin,
    AgentOverridePlugin,
    PipelinePhasePlugin,
    VectorStorePlugin,
    EmbeddingProviderPlugin,
    ApprovalStrategyPlugin,
    RulesExtensionPlugin,
    PromptEnhancerPlugin,
    EventListenerPlugin,
    WebExtensionPlugin,
    SensitiveScannerPlugin,
    CommandPlugin,
    CommandSpec,
)
from novel_agent.plugins.manager import PluginManager, EventBus
from novel_agent.plugins.lifecycle import PluginState, PluginDiagnostics
from novel_agent.plugins.contributions import (
    ContributionRegistry,
    CommandContribution,
    ViewContribution,
    ValidatorContribution,
    PipelineHookContribution,
    ExporterContribution,
    PromptEnhancerContribution,
)
from novel_agent.plugins.hooks import (
    HookRegistry,
    HookContract,
    hookspec,
    hookimpl,
    HookError,
    HookExecutionError,
    HookTimeoutError,
)
from novel_agent.plugins.services import ServiceRegistry, ServiceNotFoundError
from novel_agent.plugins.resolver import (
    DependencyResolver,
    ResolverError,
    CircularDependencyError,
    MissingDependencyError,
)
from novel_agent.plugins.capability_broker import CapabilityBroker, PermissionDeniedError
from novel_agent.plugins.legacy_adapter import LegacyPluginAdapter
from novel_agent.plugins.activation import ActivationManager

__all__ = [
    "PluginBase",
    "PluginMeta",
    "PluginType",
    "PluginContext",
    "PluginEvent",
    "PipelineHookPlugin",
    "QualityGuardPlugin",
    "ExporterPlugin",
    "LLMProviderPlugin",
    "AgentOverridePlugin",
    "PipelinePhasePlugin",
    "VectorStorePlugin",
    "EmbeddingProviderPlugin",
    "ApprovalStrategyPlugin",
    "RulesExtensionPlugin",
    "PromptEnhancerPlugin",
    "EventListenerPlugin",
    "WebExtensionPlugin",
    "SensitiveScannerPlugin",
    "CommandPlugin",
    "CommandSpec",
    "PluginManager",
    "EventBus",
    "PluginState",
    "PluginDiagnostics",
    "ActivationManager",
    "ContributionRegistry",
    "CommandContribution",
    "ViewContribution",
    "ValidatorContribution",
    "PipelineHookContribution",
    "ExporterContribution",
    "PromptEnhancerContribution",
    "HookRegistry",
    "HookContract",
    "hookspec",
    "hookimpl",
    "HookError",
    "HookExecutionError",
    "HookTimeoutError",
    "ServiceRegistry",
    "ServiceNotFoundError",
    "DependencyResolver",
    "ResolverError",
    "CircularDependencyError",
    "MissingDependencyError",
    "CapabilityBroker",
    "PermissionDeniedError",
    "LegacyPluginAdapter",
]
