"""Schemas for INKREST Human Writing Engine (HWE)."""

from __future__ import annotations

import datetime
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class HWERule(BaseModel):
    """Specification of an HWE detection rule."""

    id: str = Field(..., description="Unique rule ID e.g. HWE.STAGING.BINARY_CONTRAST")
    version: int = 1
    title: str = Field(..., description="Human readable title")
    family: str = Field(..., description="Family: staging, rhythm, language, narration, imagery, dialogue, format, longform")
    scope: List[str] = Field(default_factory=lambda: ["sentence", "paragraph"])
    detector_type: str = Field(default="regex", description="regex, phrase, rhythm, narration, dialogue, repetition")
    patterns: List[str] = Field(default_factory=list)
    severity: Literal["low", "medium", "high"] = "medium"
    confidence: float = 0.9
    thresholds: Dict[str, Any] = Field(default_factory=dict)
    fiction_policy: Dict[str, Any] = Field(default_factory=dict)
    why: str = Field(default="", description="Why this is considered a slop/template pattern")
    suggestion: str = Field(default="", description="How to fix or improve")
    source: Dict[str, Any] = Field(default_factory=dict, description="Rule provenance and upstream inspirations")
    enabled: bool = True


class HWEIssueDetail(BaseModel):
    """HWE-specific issue details."""

    rule_id: str
    family: str
    confidence: float
    start: int
    end: int
    line: int
    paragraph: int
    matched_text: str
    context_before: str = ""
    context_after: str = ""
    autofix: str = "model_patch"
    blocking: bool = False
    source: str = "local_rule"
    explainable: bool = True


class HWEIssue(BaseModel):
    """Unified issue schema conforming to INKREST audit_schema."""

    type: str
    issue_layer: Literal["plan", "text", "state", "risk"] = "text"
    severity: Literal["low", "medium", "high"] = "medium"
    audit_class: str = "WARNING"
    text: str
    why: str
    fix: str
    hwe: HWEIssueDetail

    def to_audit_dict(self) -> Dict[str, Any]:
        """Convert to legacy audit_schema issue dictionary."""
        return {
            "type": self.type,
            "issue_layer": self.issue_layer,
            "severity": self.severity,
            "audit_class": self.audit_class,
            "text": self.text,
            "why": self.why,
            "fix": self.fix,
            "hwe": self.hwe.model_dump(),
        }


class HWEScores(BaseModel):
    """Detailed dimension scores and overall template risk."""

    naturalness: int = 100       # 自然表达 (0-100)
    rhythm: int = 100            # 节奏多样 (0-100)
    narrative_trust: int = 100   # 叙事克制 (0-100)
    voice: int = 100             # 人物声线 (0-100)
    freshness: int = 100         # 表达新鲜度 (0-100)
    fidelity: int = 100          # 事实保真度 (0-100)
    template_risk: int = 0       # 综合模板风险 (0-100, 越高风险越大)
    overall_score: int = 100     # 综合文风健康分 (0-100, 越高越健康)


class HWEReport(BaseModel):
    """Quality report generated by Human Writing Engine."""

    chapter_id: Optional[str] = None
    document_revision_id: Optional[str] = None
    engine_version: str = "0.1.0"
    ruleset_version: str = "1.0.0"
    mode: str = "assist"
    char_count: int = 0
    scores: HWEScores = Field(default_factory=HWEScores)
    issues: List[HWEIssue] = Field(default_factory=list)
    issue_counts_by_family: Dict[str, int] = Field(default_factory=dict)
    issue_counts_by_severity: Dict[str, int] = Field(default_factory=dict)
    summary: str = ""
    created_at: str = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).isoformat())

    def to_audit_issues(self) -> List[Dict[str, Any]]:
        return [issue.to_audit_dict() for issue in self.issues]


class ProtectedSpan(BaseModel):
    """Fact or entity that must be protected during patch rewrite."""

    kind: str = Field(..., description="character, time, number, location, plot_fact, proper_noun")
    value: str
    policy: Literal["exact", "semantic_exact", "must_preserve"] = "exact"
    start: Optional[int] = None
    end: Optional[int] = None


class FidelityResult(BaseModel):
    """Result of validating candidate rewrite against protected spans and safety bounds."""

    passed: bool
    violations: List[str] = Field(default_factory=list)
    preserved_spans: List[ProtectedSpan] = Field(default_factory=list)
    missing_spans: List[ProtectedSpan] = Field(default_factory=list)
    edit_ratio: float = 0.0
    length_delta: int = 0


class PatchPlanItem(BaseModel):
    """Target span and instructions for a localized rewrite."""

    patch_id: str
    rule_ids: List[str] = Field(default_factory=list)
    family: str
    start: int
    end: int
    radius: Literal["phrase", "sentence", "paragraph", "dialogue", "streak"] = "sentence"
    original_text: str
    instruction: str
    risk: Literal["low", "medium", "high"] = "medium"
    protected_spans: List[ProtectedSpan] = Field(default_factory=list)


class HWEPatchCandidate(BaseModel):
    """Generated localized patch proposal ready for diff and user review."""

    patch_id: str
    rule_ids: List[str] = Field(default_factory=list)
    start: int
    end: int
    original_text: str
    candidate_text: str
    instruction: str
    fidelity: FidelityResult
    utility: float = 0.0
    quality_gain: int = 0
    diff_unified: str = ""
    status: Literal["pending", "accepted", "rejected"] = "pending"
    created_at: str = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).isoformat())
